import Foundation

public enum LanguageOption: String, CaseIterable, Identifiable {
    case system = ""
    case english = "en"
    case german = "de"
    case french = "fr"
    case dutch = "nl"
    case spanish = "es"
    case italian = "it"
    case norwegian = "nb"
    case swedish = "sv"
    case portuguese = "pt"
    
    public var id: String { rawValue }
    
    public var displayName: String {
        switch self {
        case .system: return "System Default"
        case .english: return "English"
        case .german: return "Deutsch"
        case .french: return "Français"
        case .dutch: return "Nederlands"
        case .spanish: return "Español"
        case .italian: return "Italiano"
        case .norwegian: return "Norsk bokmål"
        case .swedish: return "Svenska"
        case .portuguese: return "Português"
        }
    }
}

public struct L10n {
    private static let translations: [String: [String: String]] = [
        "en": [
            "app_name": "EV Charge Calculator",
            "current_charge": "Current Charge",
            "target_charge": "Target Charge",
            "charge_required": "Charge Required",
            "energy_needed": "Energy Needed",
            "soc_increase": "SOC Increase",
            "effective_capacity": "Effective Capacity",
            "settings": "Settings",
            "open_settings": "Open Settings",
            "battery_capacity": "Battery Capacity",
            "state_of_health": "State of Health (SOH)",
            "charge_losses": "Charge Losses",
            "quick_presets": "Quick Presets",
            "preset_daily_80": "Daily 80%",
            "preset_top_up_90": "Top Up 90%",
            "preset_road_trip_100": "Road Trip 100%",
            "target_lower_warning": "Target charge is lower than current charge. Please adjust values.",
            "target_equal_info": "Target charge equals current charge - no charging needed.",
            "auto_adjusted_format": "Auto-adjusted: %@",
            "ev_settings": "EV Settings",
            "done": "Done",
            "back": "Back",
            "battery_configuration": "Battery Configuration",
            "calculated_values": "Calculated Values",
            "usable_capacity": "Usable Capacity (10-90%)",
            "settings_description": "Adjust these values based on your EV's specifications. Battery capacity is the total kWh rating, SOH represents battery degradation over time, and charge losses account for charging inefficiencies.",
            "goe_integration": "go-eCharger Integration",
            "goe_control_title": "go-eCharger Control",
            "enable_goe": "Enable go-eCharger",
            "enable_goe_desc": "Push charge limits to charger",
            "charger_ip_address": "Charger IP Address",
            "energy_limit_format": "Energy limit: %.1f kWh",
            "energy_limit_wh_format": "(%d Wh)",
            "btn_set_energy_limit": "Set Energy Limit",
            "btn_pushing": "Pushing…",
            "goe_limit_success": "✓ Energy limit set successfully",
            "test": "Test",
            "testing": "Testing…",
            "connection_status": "Connection Status:",
            "not_tested": "Not tested",
            "connected": "Connected",
            "failed": "Failed",
            "error_required": "Required",
            "error_invalid_number": "Invalid number",
            "error_cannot_be_negative": "Cannot be negative",
            "error_cannot_exceed_100": "Cannot exceed 100%",
            "error_current_exceeds_target": "Current charge cannot exceed target charge",
            "error_target_higher_than_current": "Target charge should be higher than current charge",
            "language": "Language",
            "system_default": "System Default",
            "incl_losses_format": "incl. %d%% loss"
        ],
        "de": [
            "app_name": "EV Lade-Rechner",
            "current_charge": "Aktueller Ladestand",
            "target_charge": "Zielladestand",
            "charge_required": "Erforderliche Ladung",
            "energy_needed": "Benötigte Energie",
            "soc_increase": "SOC-Zuwachs",
            "effective_capacity": "Effektive Kapazität",
            "settings": "Einstellungen",
            "open_settings": "Einstellungen öffnen",
            "battery_capacity": "Batteriekapazität",
            "state_of_health": "Gesundheitszustand (SOH)",
            "charge_losses": "Ladeverluste",
            "quick_presets": "Schnellwahl",
            "preset_daily_80": "Alltag 80%",
            "preset_top_up_90": "Nachladen 90%",
            "preset_road_trip_100": "Reise 100%",
            "target_lower_warning": "Der Zielladestand ist niedriger als der aktuelle Ladestand. Bitte Werte anpassen.",
            "target_equal_info": "Zielladestand entspricht dem aktuellen Ladestand - kein Laden erforderlich.",
            "auto_adjusted_format": "Automatisch angepasst: %@",
            "ev_settings": "EV-Einstellungen",
            "done": "Fertig",
            "back": "Zurück",
            "battery_configuration": "Batterie-Konfiguration",
            "calculated_values": "Berechnete Werte",
            "usable_capacity": "Nutzbare Kapazität (10-90%)",
            "settings_description": "Passen Sie diese Werte an die Spezifikationen Ihres Elektrofahrzeugs an. Die Batteriekapazität ist die gesamte kWh-Angabe, der SOH steht für die Batteriedegradation über die Zeit und die Ladeverluste berücksichtigen Ladeineffizienzen.",
            "goe_integration": "go-eCharger Integration",
            "goe_control_title": "go-eCharger Steuerung",
            "enable_goe": "go-eCharger aktivieren",
            "enable_goe_desc": "Ladelimit an die Ladestation senden",
            "charger_ip_address": "IP-Adresse der Ladestation",
            "energy_limit_format": "Energielimit: %.1f kWh",
            "energy_limit_wh_format": "(%d Wh)",
            "btn_set_energy_limit": "Energielimit setzen",
            "btn_pushing": "Wird übertragen…",
            "goe_limit_success": "✓ Energielimit erfolgreich gesetzt",
            "test": "Testen",
            "testing": "Wird getestet…",
            "connection_status": "Verbindungsstatus:",
            "not_tested": "Nicht getestet",
            "connected": "Verbunden",
            "failed": "Fehlgeschlagen",
            "error_required": "Erforderlich",
            "error_invalid_number": "Ungültige Zahl",
            "error_cannot_be_negative": "Darf nicht negativ sein",
            "error_cannot_exceed_100": "Darf 100% nicht überschreiten",
            "error_current_exceeds_target": "Aktueller Ladestand kann den Zielladestand nicht überschreiten",
            "error_target_higher_than_current": "Zielladestand sollte höher als der aktuelle Ladestand sein",
            "language": "Sprache",
            "system_default": "Systemstandard",
            "incl_losses_format": "inkl. %d%% Verlust"
        ],
        "fr": [
            "app_name": "Calculateur de Recharge VE",
            "current_charge": "Charge actuelle",
            "target_charge": "Charge cible",
            "charge_required": "Charge requise",
            "energy_needed": "Énergie nécessaire",
            "soc_increase": "Augmentation du SOC",
            "effective_capacity": "Capacité effective",
            "settings": "Paramètres",
            "open_settings": "Ouvrir les paramètres",
            "battery_capacity": "Capacité de batterie",
            "state_of_health": "État de santé (SOH)",
            "charge_losses": "Pertes de charge",
            "quick_presets": "Préréglages rapides",
            "preset_daily_80": "Quotidien 80%",
            "preset_top_up_90": "Appoint 90%",
            "preset_road_trip_100": "Voyage 100%",
            "target_lower_warning": "La charge cible est inférieure à la charge actuelle. Veuillez ajuster les valeurs.",
            "target_equal_info": "La charge cible est égale à la charge actuelle - aucune recharge requise.",
            "auto_adjusted_format": "Ajusté automatiquement : %@",
            "ev_settings": "Paramètres VE",
            "done": "Terminé",
            "back": "Retour",
            "battery_configuration": "Configuration de la batterie",
            "calculated_values": "Valeurs calculées",
            "usable_capacity": "Capacité utilisable (10-90%)",
            "settings_description": "Ajustez ces valeurs selon les caractéristiques de votre véhicule électrique. La capacité de la batterie est la valeur totale en kWh, le SOH représente la dégradation de la batterie au fil du temps et les pertes de charge tiennent compte des inefficacités.",
            "goe_integration": "Intégration go-eCharger",
            "goe_control_title": "Contrôle go-eCharger",
            "enable_goe": "Activer go-eCharger",
            "enable_goe_desc": "Envoyer les limites de charge à la borne",
            "charger_ip_address": "Adresse IP de la borne",
            "energy_limit_format": "Limite d'énergie : %.1f kWh",
            "energy_limit_wh_format": "(%d Wh)",
            "btn_set_energy_limit": "Définir la limite d'énergie",
            "btn_pushing": "Envoi…",
            "goe_limit_success": "✓ Limite d'énergie définie avec succès",
            "test": "Tester",
            "testing": "Test en cours…",
            "connection_status": "État de la connexion :",
            "not_tested": "Non testé",
            "connected": "Connecté",
            "failed": "Échec",
            "error_required": "Obligatoire",
            "error_invalid_number": "Nombre invalide",
            "error_cannot_be_negative": "Ne peut pas être négatif",
            "error_cannot_exceed_100": "Ne peut pas dépasser 100%",
            "error_current_exceeds_target": "La charge actuelle ne peut pas dépasser la charge cible",
            "error_target_higher_than_current": "La charge cible doit être supérieure à la charge actuelle",
            "language": "Langue",
            "system_default": "Par défaut du système",
            "incl_losses_format": "incl. %d%% pertes"
        ],
        "nl": [
            "app_name": "EV Laad Calculator",
            "current_charge": "Huidige lading",
            "target_charge": "Doellading",
            "charge_required": "Vereiste lading",
            "energy_needed": "Benodigde energie",
            "soc_increase": "SOC-toename",
            "effective_capacity": "Effectieve capaciteit",
            "settings": "Instellingen",
            "open_settings": "Instellingen openen",
            "battery_capacity": "Batterijcapaciteit",
            "state_of_health": "Gezondheidstoestand (SOH)",
            "charge_losses": "Laadverliezen",
            "quick_presets": "Snelle voorkeuren",
            "preset_daily_80": "Dagelijks 80%",
            "preset_top_up_90": "Bijladen 90%",
            "preset_road_trip_100": "Reis 100%",
            "target_lower_warning": "Doellading is lager dan huidige lading. Pas de waarden aan.",
            "target_equal_info": "Doellading is gelijk aan huidige lading - opladen niet nodig.",
            "auto_adjusted_format": "Automatisch aangepast: %@",
            "ev_settings": "EV-instellingen",
            "done": "Gereed",
            "back": "Terug",
            "battery_configuration": "Batterijconfiguratie",
            "calculated_values": "Berekende waarden",
            "usable_capacity": "Bruikbare capaciteit (10-90%)",
            "settings_description": "Pas deze waarden aan volgens de specificaties van uw EV. Batterijcapaciteit is de totale kWh, SOH geeft batterijdegradatie in de tijd weer en laadverliezen houden rekening met laadinefficiëntie.",
            "goe_integration": "go-eCharger integratie",
            "goe_control_title": "go-eCharger bediening",
            "enable_goe": "go-eCharger inschakelen",
            "enable_goe_desc": "Laadlimieten doorsturen naar lader",
            "charger_ip_address": "IP-adres van lader",
            "energy_limit_format": "Energielimiet: %.1f kWh",
            "energy_limit_wh_format": "(%d Wh)",
            "btn_set_energy_limit": "Energielimiet instellen",
            "btn_pushing": "Verzenden…",
            "goe_limit_success": "✓ Energielimiet succesvol ingesteld",
            "test": "Testen",
            "testing": "Testen…",
            "connection_status": "Verbindingsstatus:",
            "not_tested": "Niet getest",
            "connected": "Verbonden",
            "failed": "Mislukt",
            "error_required": "Verplicht",
            "error_invalid_number": "Ongeldig getal",
            "error_cannot_be_negative": "Mag niet negatief zijn",
            "error_cannot_exceed_100": "Mag niet hoger zijn dan 100%",
            "error_current_exceeds_target": "Huidige lading kan niet hoger zijn dan doellading",
            "error_target_higher_than_current": "Doellading moet hoger zijn dan huidige lading",
            "language": "Taal",
            "system_default": "Systeemstandaard",
            "incl_losses_format": "incl. %d%% verlies"
        ],
        "es": [
            "app_name": "Calculadora de Carga VE",
            "current_charge": "Carga actual",
            "target_charge": "Carga objetivo",
            "charge_required": "Carga requerida",
            "energy_needed": "Energía necesaria",
            "soc_increase": "Aumento del SOC",
            "effective_capacity": "Capacidad efectiva",
            "settings": "Ajustes",
            "open_settings": "Abrir ajustes",
            "battery_capacity": "Capacidad de batería",
            "state_of_health": "Estado de salud (SOH)",
            "charge_losses": "Pérdidas de carga",
            "quick_presets": "Preajustes rápidos",
            "preset_daily_80": "Diario 80%",
            "preset_top_up_90": "Recarga 90%",
            "preset_road_trip_100": "Viaje 100%",
            "target_lower_warning": "La carga objetivo es menor que la carga actual. Ajuste los valores.",
            "target_equal_info": "La carga objetivo es igual a la carga actual - no requiere carga.",
            "auto_adjusted_format": "Ajustado automáticamente: %@",
            "ev_settings": "Ajustes del VE",
            "done": "Listo",
            "back": "Atrás",
            "battery_configuration": "Configuración de la batería",
            "calculated_values": "Valores calculados",
            "usable_capacity": "Capacidad utilizable (10-90%)",
            "settings_description": "Ajuste estos valores según las especificaciones de su VE. La capacidad de la batería es el valor total en kWh, el SOH representa la degradación de la batería con el tiempo y las pérdidas de carga consideran las ineficiencias.",
            "goe_integration": "Integración go-eCharger",
            "goe_control_title": "Control go-eCharger",
            "enable_goe": "Activar go-eCharger",
            "enable_goe_desc": "Enviar límites de carga al cargador",
            "charger_ip_address": "Dirección IP del cargador",
            "energy_limit_format": "Límite de energía: %.1f kWh",
            "energy_limit_wh_format": "(%d Wh)",
            "btn_set_energy_limit": "Establecer límite de energía",
            "btn_pushing": "Enviando…",
            "goe_limit_success": "✓ Límite de energía establecido con éxito",
            "test": "Probar",
            "testing": "Probando…",
            "connection_status": "Estado de conexión:",
            "not_tested": "No probado",
            "connected": "Conectado",
            "failed": "Error",
            "error_required": "Obligatorio",
            "error_invalid_number": "Número inválido",
            "error_cannot_be_negative": "No puede ser negativo",
            "error_cannot_exceed_100": "No puede superar el 100%",
            "error_current_exceeds_target": "La carga actual no puede superar la carga objetivo",
            "error_target_higher_than_current": "La carga objetivo debe ser mayor que la carga actual",
            "language": "Idioma",
            "system_default": "Predeterminado del sistema",
            "incl_losses_format": "incl. %d%% pérdidas"
        ],
        "it": [
            "app_name": "Calcolatore Ricarica VE",
            "current_charge": "Carica attuale",
            "target_charge": "Carica desiderata",
            "charge_required": "Ricarica richiesta",
            "energy_needed": "Energia necessaria",
            "soc_increase": "Aumento SOC",
            "effective_capacity": "Capacità effettiva",
            "settings": "Impostazioni",
            "open_settings": "Apri impostazioni",
            "battery_capacity": "Capacità batteria",
            "state_of_health": "Stato di salute (SOH)",
            "charge_losses": "Perdite di ricarica",
            "quick_presets": "Preimpostazioni rapide",
            "preset_daily_80": "Giornaliero 80%",
            "preset_top_up_90": "Rabbocco 90%",
            "preset_road_trip_100": "Viaggio 100%",
            "target_lower_warning": "La carica desiderata è inferiore a quella attuale. Regola i valori.",
            "target_equal_info": "La carica desiderata è pari a quella attuale - nessuna ricarica necessaria.",
            "auto_adjusted_format": "Regolato automaticamente: %@",
            "ev_settings": "Impostazioni VE",
            "done": "Fine",
            "back": "Indietro",
            "battery_configuration": "Configurazione batteria",
            "calculated_values": "Valori calcolati",
            "usable_capacity": "Capacità utilizzabile (10-90%)",
            "settings_description": "Regola questi valori in base alle specifiche del tuo veicolo elettrico. La capacità della batteria è il valore totale in kWh, il SOH rappresenta il degrado della batteria nel tempo e le perdite tengono conto delle inefficienze.",
            "goe_integration": "Integrazione go-eCharger",
            "goe_control_title": "Controllo go-eCharger",
            "enable_goe": "Abilita go-eCharger",
            "enable_goe_desc": "Invia i limiti di carica alla stazione",
            "charger_ip_address": "Indirizzo IP stazione",
            "energy_limit_format": "Limite energia: %.1f kWh",
            "energy_limit_wh_format": "(%d Wh)",
            "btn_set_energy_limit": "Imposta limite energia",
            "btn_pushing": "Invio…",
            "goe_limit_success": "✓ Limite di energia impostato con successo",
            "test": "Test",
            "testing": "Test in corso…",
            "connection_status": "Stato connessione:",
            "not_tested": "Non testato",
            "connected": "Connesso",
            "failed": "Non riuscito",
            "error_required": "Obbligatorio",
            "error_invalid_number": "Numero non valido",
            "error_cannot_be_negative": "Non può essere negativo",
            "error_cannot_exceed_100": "Non può superare il 100%",
            "error_current_exceeds_target": "La carica attuale non può superare quella desiderata",
            "error_target_higher_than_current": "La carica desiderata deve essere superiore a quella attuale",
            "language": "Lingua",
            "system_default": "Predefinito di sistema",
            "incl_losses_format": "incl. %d%% perdite"
        ],
        "nb": [
            "app_name": "EV Ladekalkulator",
            "current_charge": "Nåværende lading",
            "target_charge": "Mållading",
            "charge_required": "Nødvendig lading",
            "energy_needed": "Nødvendig energi",
            "soc_increase": "SOC-økning",
            "effective_capacity": "Effektiv kapasitet",
            "settings": "Innstillinger",
            "open_settings": "Åpne innstillinger",
            "battery_capacity": "Batterikapasitet",
            "state_of_health": "Helsetilstand (SOH)",
            "charge_losses": "Ladetap",
            "quick_presets": "Hurtigvalg",
            "preset_daily_80": "Daglig 80%",
            "preset_top_up_90": "Påfylling 90%",
            "preset_road_trip_100": "Biltur 100%",
            "target_lower_warning": "Mållading er lavere enn nåværende lading. Vennligst juster verdiene.",
            "target_equal_info": "Mållading er lik nåværende lading - ingen lading nødvendig.",
            "auto_adjusted_format": "Automatisk justert: %@",
            "ev_settings": "EV-innstillinger",
            "done": "Ferdig",
            "back": "Tilbake",
            "battery_configuration": "Batterikonfigurasjon",
            "calculated_values": "Beregnede verdier",
            "usable_capacity": "Brukbar kapasitet (10-90%)",
            "settings_description": "Juster disse verdiene etter din elbils spesifikasjoner. Batterikapasitet er total kWh, SOH representerer batteriforringelse over tid, og ladetap tar hensyn til ineffektivitet.",
            "goe_integration": "go-eCharger-integrasjon",
            "goe_control_title": "go-eCharger-styring",
            "enable_goe": "Aktiver go-eCharger",
            "enable_goe_desc": "Send ladegrenser til lader",
            "charger_ip_address": "Laderens IP-adresse",
            "energy_limit_format": "Energigrense: %.1f kWh",
            "energy_limit_wh_format": "(%d Wh)",
            "btn_set_energy_limit": "Sett energigrense",
            "btn_pushing": "Sender…",
            "goe_limit_success": "✓ Energigrense satt",
            "test": "Test",
            "testing": "Tester…",
            "connection_status": "Tilkoblingsstatus:",
            "not_tested": "Ikke testet",
            "connected": "Tilkoblet",
            "failed": "Mislyktes",
            "error_required": "Påkrevd",
            "error_invalid_number": "Ugyldig tall",
            "error_cannot_be_negative": "Kan ikke være negativt",
            "error_cannot_exceed_100": "Kan ikke overskride 100%",
            "error_current_exceeds_target": "Nåværende lading kan ikke overskride mållading",
            "error_target_higher_than_current": "Mållading bør være høyere enn nåværende lading",
            "language": "Språk",
            "system_default": "Systemstandard",
            "incl_losses_format": "inkl. %d%% tap"
        ],
        "sv": [
            "app_name": "EV Laddkalkylator",
            "current_charge": "Nuvarande laddning",
            "target_charge": "Målladdning",
            "charge_required": "Nödvändig laddning",
            "energy_needed": "Energi som behövs",
            "soc_increase": "SOC-ökning",
            "effective_capacity": "Effektiv kapacitet",
            "settings": "Inställningar",
            "open_settings": "Öppna inställningar",
            "battery_capacity": "Batterikapacitet",
            "state_of_health": "Hälsotillstånd (SOH)",
            "charge_losses": "Laddningsförluster",
            "quick_presets": "Snabbval",
            "preset_daily_80": "Vardag 80%",
            "preset_top_up_90": "Påfyllning 90%",
            "preset_road_trip_100": "Resa 100%",
            "target_lower_warning": "Målladdning är lägre än nuvarande laddning. Justera värdena.",
            "target_equal_info": "Målladdning är lika med nuvarande laddning - ingen laddning behövs.",
            "auto_adjusted_format": "Automatiskt justerad: %@",
            "ev_settings": "EV-inställningar",
            "done": "Klar",
            "back": "Tillbaka",
            "battery_configuration": "Batterikonfiguration",
            "calculated_values": "Beräknade värden",
            "usable_capacity": "Användbar kapacitet (10-90%)",
            "settings_description": "Justera dessa värden enligt din elbils specifikationer. Batterikapaciteten är den totala kWh-angivelsen, SOH visar batteridegradering över tid och laddförluster tar hänsyn till ineffektivitet.",
            "goe_integration": "go-eCharger-integration",
            "goe_control_title": "go-eCharger-styrning",
            "enable_goe": "Aktivera go-eCharger",
            "enable_goe_desc": "Skicka laddgränser till laddaren",
            "charger_ip_address": "Laddarens IP-adress",
            "energy_limit_format": "Energigräns: %.1f kWh",
            "energy_limit_wh_format": "(%d Wh)",
            "btn_set_energy_limit": "Ställ in energigräns",
            "btn_pushing": "Skickar…",
            "goe_limit_success": "✓ Energigräns inställd",
            "test": "Testa",
            "testing": "Testar…",
            "connection_status": "Anslutningsstatus:",
            "not_tested": "Inte testad",
            "connected": "Ansluten",
            "failed": "Misslyckades",
            "error_required": "Obligatoriskt",
            "error_invalid_number": "Ogiltigt nummer",
            "error_cannot_be_negative": "Kan inte vara negativt",
            "error_cannot_exceed_100": "Får inte överstiga 100%",
            "error_current_exceeds_target": "Nuvarande laddning kan inte överstiga målladdning",
            "error_target_higher_than_current": "Målladdning bör vara högre än nuvarande laddning",
            "language": "Språk",
            "system_default": "Systemstandard",
            "incl_losses_format": "inkl. %d%% förlust"
        ],
        "pt": [
            "app_name": "Calculadora de Carga VE",
            "current_charge": "Carga atual",
            "target_charge": "Carga pretendida",
            "charge_required": "Carga necessária",
            "energy_needed": "Energia necessária",
            "soc_increase": "Aumento de SOC",
            "effective_capacity": "Capacidade efetiva",
            "settings": "Definições",
            "open_settings": "Abrir definições",
            "battery_capacity": "Capacidade da bateria",
            "state_of_health": "Estado de saúde (SOH)",
            "charge_losses": "Perdas de carga",
            "quick_presets": "Predefinições rápidas",
            "preset_daily_80": "Diário 80%",
            "preset_top_up_90": "Recarga 90%",
            "preset_road_trip_100": "Viagem 100%",
            "target_lower_warning": "A carga pretendida é inferior à atual. Ajuste os valores.",
            "target_equal_info": "A carga pretendida é igual à carga atual - não é necessário carregar.",
            "auto_adjusted_format": "Ajustado automaticamente: %@",
            "ev_settings": "Definições do VE",
            "done": "Concluído",
            "back": "Voltar",
            "battery_configuration": "Configuração da bateria",
            "calculated_values": "Valores calculados",
            "usable_capacity": "Capacidade utilizável (10-90%)",
            "settings_description": "Ajuste estes valores de acordo com as especificações do seu VE. A capacidade da bateria é o valor total em kWh, o SOH representa a degradação da bateria ao longo do tempo e as perdas de carga consideram as ineficiências.",
            "goe_integration": "Integração go-eCharger",
            "goe_control_title": "Controlo go-eCharger",
            "enable_goe": "Ativar go-eCharger",
            "enable_goe_desc": "Enviar limites de carga para o carregador",
            "charger_ip_address": "Endereço IP do carregador",
            "energy_limit_format": "Limite de energia: %.1f kWh",
            "energy_limit_wh_format": "(%d Wh)",
            "btn_set_energy_limit": "Definir limite de energia",
            "btn_pushing": "A enviar…",
            "goe_limit_success": "✓ Limite de energia definido com sucesso",
            "test": "Testar",
            "testing": "A testar…",
            "connection_status": "Estado da ligação:",
            "not_tested": "Não testado",
            "connected": "Ligado",
            "failed": "Falha",
            "error_required": "Obrigatório",
            "error_invalid_number": "Número inválido",
            "error_cannot_be_negative": "Não pode ser negativo",
            "error_cannot_exceed_100": "Não pode exceder 100%",
            "error_current_exceeds_target": "A carga atual não pode exceder a pretendida",
            "error_target_higher_than_current": "A carga pretendida deve ser superior à atual",
            "language": "Idioma",
            "system_default": "Padrão do sistema",
            "incl_losses_format": "incl. %d%% perdas"
        ]
    ]
    
    public static func tr(_ key: String, lang: String = "") -> String {
        let activeLang: String
        if lang.isEmpty {
            let preferred = Locale.preferredLanguages.first?.prefix(2).lowercased() ?? "en"
            activeLang = translations.keys.contains(preferred) ? preferred : "en"
        } else {
            activeLang = translations.keys.contains(lang) ? lang : "en"
        }
        
        return translations[activeLang]?[key] ?? translations["en"]?[key] ?? key
    }
}
